config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from ipm_learning.pages.views import AboutPageView, HomePageView, AgencyPageView, subscription
from ipm_learning.content.models import Course

import requests
from django.http import HttpResponse

def serve_ads_txt(request):
    with open('ipm_learning/static/ads.txt', 'r') as file:
        data = file.read()
    return HttpResponse(data, content_type="text/plain")


info_dict = {
    'queryset': Course.objects.all(),
}

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("bahasa-ibu/", AgencyPageView.as_view(), name="bahasa_ibu"),
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
    #     "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # Content
    path("learn/", include("ipm_learning.content.urls", namespace="content")),
    path("order/", include("ipm_learning.order.urls", namespace="order")),
    path("comeback/", include("ipm_learning.comeback.urls", namespace="comeback")),

    # User management
    path("users/", include("ipm_learning.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    
    # Your stuff: custom urls includes go here
    path('subscribe/', subscription, name="subscription"),
    # path("email-test/",TemplateView.as_view(template_name="account/email/payment_success.html")),
    path('tinymce/', include('tinymce.urls')),
    # path('forest', include('django_forest.urls')),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('ads.txt', serve_ads_txt, name='ads_txt'),
    path('sitemap.xml', sitemap,
        {'sitemaps': {'course': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ipm_learning/content/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, ContentDetailView, CourseLibraryView, EventListView

app_name = "content"

urlpatterns = [
    path("courses/", CourseListView.as_view(), name="course-list"),
    # path("events/", EventListView.as_view(), name="event-list"),
    path("library/", CourseLibraryView.as_view(), name="course-library"),
    path("<slug>/", CourseDetailView.as_view(), name="course-detail"),
    path("<slug>/<content_slug>/", ContentDetailView.as_view(), name="content-detail"),
]

ipm_learning/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path('order-summary/', views.CartView.as_view(), name='summary'),
    path('order-list/', views.OrderListView.as_view(), name='order-list'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('webhooks/xendit/', views.xendit_webhook, name='xendit-webhook'),
]

ipm_learning/users/urls.py
from django.urls import path

from ipm_learning.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    BulkUploadView
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    # path('bulk-import/', BulkUploadView.as_view(), name='bulk-import'),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

ipm_learning/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


from allauth.account.views import PasswordResetView
from django.conf import settings
from django.dispatch import receiver
from django.http import HttpRequest
from django.middleware.csrf import get_token
from django.db.models.signals import post_save
from django.db import transaction


class User(AbstractUser):
    """Default user for ipm_learning."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    phone_number = CharField(max_length=30)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

ipm_learning/order/forms.py
from django import forms
from .models import OrderItem
from ipm_learning.content.models import Course

class AddToCartForm(forms.ModelForm):

    class Meta:
        model = OrderItem
        exclude = ['order','course']
        widgets = {'any_field': forms.HiddenInput(),}
        # fields = ['quantity', 'colour', 'size']

class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter your code',
    }))

ipm_learning/comeback/views.py
from django.shortcuts import render
from datetime import date
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .models import ComebackJourney, ComebackRecord
from ipm_learning.order.models import OrderItem, CourseRecord
from ipm_learning.order.utils import get_or_set_order_session
from django.shortcuts import redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .models import ComebackWaitlist
from django.contrib.auth.decorators import login_required


def comeback_main(request):
    journey = ComebackJourney.objects.filter(is_active=True).first()
    registration = False
    current_date = date.today()
    
    if journey and journey.signup_start_date <= current_date <= journey.signup_end_date and journey.remaining_spots > 0:
        registration = True

    
    # Check if the user is authenticated and if they are on the waitlist
    on_waitlist = False
    if request.user.is_authenticated:
        on_waitlist = ComebackWaitlist.objects.filter(user=request.user).exists()

    context = {
        'journey': journey,
        'registration': registration,
        'on_waitlist': on_waitlist,
    }
    
    if request.method == 'POST':
        order = get_or_set_order_session(request)
        
        if not request.user.is_authenticated:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
        else:
            if request.POST.get('pmt_type') == 'monthly':
                is_monthly_pmt = True
            else:
                is_monthly_pmt = False
                
            comeback_record = ComebackRecord.objects.filter(comeback=journey, user=request.user).first()
            
            if comeback_record and comeback_record.is_active:
                messages.info(request, "This item is already in your library")
                return redirect("content:course-library")
            else:
                if comeback_record:
                    comeback_record.delete()
                comeback_record = ComebackRecord.objects.create(
                user = request.user,
                comeback = journey,
                is_monthly_pmt = is_monthly_pmt,
                one_time_price = journey.one_time_price,
                monthly_price = journey.monthly_price,
                num_monthly_pmts = journey.num_monthly_pmts,   
            )
        
            item_filter_lst = order.order_items.filter(comeback_record=comeback_record)
            
            if not item_filter_lst.exists():
                new_item = OrderItem.objects.create(
                    comeback_record = comeback_record,
                    order = order,
                    tickets = 1,
                )
                return redirect("order:summary")
            else:
                messages.info(request, "This item is already in your cart")
                return redirect("order:summary") 
    
    return render(request, 'comeback/comeback_main.html', context)



class ComebackJourneyDetail(LoginRequiredMixin, generic.DetailView):
    model = ComebackJourney
    template_name = "comeback/comeback_detail.html"
    context_object_name = "comeback_journey"
    slug_url_kwarg = 'slug'
    slug_field = 'slug'  # Adjust the slug field accordingly

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        user = self.request.user
        comeback_journey = self.get_object()

        try:
            # Check if user has an associated ComebackRecord
            comeback_record = ComebackRecord.objects.get(user=user, comeback=comeback_journey)

            # Check if the record is live
            comeback_record.is_live = comeback_record.comeback.course_start_date <= date.today()

            # Retrieve CourseRecords only if the record is live
            if comeback_record.is_live:
                context['course_records'] = CourseRecord.objects.filter(user=user, comeback_record=comeback_record)
            else:
                context['course_records'] = []

            context['comeback_record'] = comeback_record
        except ComebackRecord.DoesNotExist:
            # If no associated ComebackRecord is found, set course_records to an empty list
            context['course_records'] = []

        return context
    
    
class AddToWaitlistView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
            # Create a new waitlist entry for the current user
            ComebackWaitlist.objects.create(user=request.user)
            # Redirect the user to a thank you page or back to the main page
            return redirect(reverse('comeback:comeback_main') + '#journeySection')
        
@login_required
def add_to_waitlist_view(request):
    if request.method == 'POST':
        # Create a new waitlist entry for the current user
        ComebackWaitlist.objects.create(user=request.user)
        # Redirect the user to a thank you page or back to the main page
        return redirect(reverse('comeback:comeback_main') + '#waitlist')

ipm_learning/pages/views.py
from django.shortcuts import redirect
from django.contrib import messages
from django.shortcuts import render
from django.views import generic
from django.db.models import Q
from ipm_learning.content.models import Course
from .models import PromotedCourse, Testimonial, TeamMember, PageContent, Article
from django.conf import settings
from mailchimp_marketing import Client
from mailchimp_marketing.api_client import ApiClientError

# Create your views here.

class AboutPageView(generic.TemplateView):
    template_name = 'pages/about.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_content'] = PageContent.objects.get(page_title='About')
        return context
    
class AgencyPageView(generic.TemplateView):
    template_name = 'pages/bahasa_ibu.html'
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['page_content'] = PageContent.objects.get(page_title='About')
    #     return context


class HomePageView(generic.TemplateView):
    template_name = 'pages/home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        events = Course.objects.filter(
            (Q(course_type="Event") | Q(course_type="Bootcamp")) & Q(active=True)
            ).order_by('event_datetime')[:3]
        
        # courses = Course.objects.filter(
        #     Q(course_type="Course") & Q(active=True)
        # )[:6]
        
        promo_courses = PromotedCourse.objects.all()
        
        testimonials = Testimonial.objects.all().order_by('?')[:6]
        teammembers = TeamMember.objects.all()
        articles = Article.objects.order_by().order_by('-id')[:4]
        
        context['next_event'] = events[:1].first()
        context['remaining_events'] = events[1:]
        context['courses'] = promo_courses
        context['testimonials'] = testimonials
        context['teammembers'] = teammembers
        context['articles'] = articles
        return context
    


# Mailchimp Settings
api_key = settings.MAILCHIMP_API_KEY
server = settings.MAILCHIMP_DATA_CENTER
list_id = settings.MAILCHIMP_EMAIL_LIST_ID
   

def subscription(request):
    if request.method == "POST":
        email = request.POST['email']
        next = request.POST['next']

        # Communicate with Mailchimp API
        mailchimp = Client()
        mailchimp.set_config({
            "api_key": api_key,
            "server": server,
        })

        member_info = {
            "email_address": email,
            "status": "subscribed",
        }

        try:
            response = mailchimp.lists.add_list_member(list_id, member_info)
            print("response: {}".format(response))
            messages.info(request, "Sudah Berlangganan!")
        except ApiClientError as error:
            print("An exception occurred: {}".format(error.text))
            messages.info(request, "Gagal Berlangganan karena format yang salah atau sudah berlangganan")

        # messages.success(request, "Email received. thank You! ")
    return redirect(next)

ipm_learning/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView, TemplateView
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from ipm_learning.order.models import Order
import io, csv

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        queryset = Order.objects.filter(
            user=user
        )
        context["orders"] = queryset
        return context
  


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name", "phone_number"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class BulkUploadView(TemplateView):
    def get(self, request):
        template_name = 'users/bulk_import.html'
        return render(request, template_name)

    def post(self, request):
        paramFile = io.TextIOWrapper(request.FILES['userfile'].file)
        portfolio1 = csv.DictReader(paramFile)
        list_of_dict = list(portfolio1)
        objs = [
            User(
                name=row['name'],
                username=row['email'],
                email=row['email'],
            )
            for row in list_of_dict
        ]
        try:
            msg = User.objects.bulk_create(objs)
            returnmsg = {"status_code": 200}
            print('imported successfully')
        except Exception as e:
            print('Error While Importing Data: ', e)
            returnmsg = {"status_code": 500}
            


        return JsonResponse(returnmsg)

ipm_learning/templates/order/old_order_summary.html
{% extends "base.html" %}

{% block content %}


  <div class="container mx-auto mt-10">
    <div class="flex my-10">
      <div class="w-3/4 bg-white px-10 py-10">
        <div class="flex justify-between border-b pb-8">
          <h1 class="font-semibold text-2xl">Shopping Cart</h1>
          <h2 class="font-semibold text-2xl">{{ order.get_order_item_count }} Items</h2>
        </div>
        <div class="flex mt-10 mb-5">
          <h3 class="font-semibold text-gray-600 text-xs uppercase w-2/5">Product Details</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5 text-center">List Price</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5 text-center">Discount</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5 text-center">Final Price</h3>
        </div>
        {% for item in order.order_items.all %}
        <div class="flex items-center hover:bg-gray-100 -mx-8 px-6 py-5">
          <div class="flex w-2/5"> <!-- product -->
            <div class="w-20">
            <a href="{{ item.course.get_absolute_url }}">
              <img class="h-24" src="{{ item.course.thumbnail.url }}" alt="">
            </a>
            </div>
            <div class="flex flex-col justify-between ml-4 flex-grow">
            <a href="{{ item.course.get_absolute_url }}">
              <span class="font-bold text-sm">{{ item.course.name }}</span></a>
              <span class="text-black-500 text-xs">{{ item.course.category }} | {{ item.course.course_type }}</span>
              <a href="{% url 'order:remove-from-cart' item.id %}" class="font-semibold hover:text-red-500 text-gray-500 text-xs">Remove</a>
            </div>
          </div>
          <span class="text-center w-1/5 font-semibold text-sm">{{ item.course.get_price }}</span>
          <span class="text-center w-1/5 font-semibold text-sm">{{ item.course.get_discount_pct }}</span>
          <span class="text-center w-1/5 font-semibold text-sm">{{ item.course.get_discount_price }}</span>
        </div>
        {% endfor %}
        

        

        <a href="{% url 'content:course-list' %}" class="flex font-semibold text-indigo-600 text-sm mt-10">
      
          <svg class="fill-current mr-2 text-indigo-600 w-4" viewBox="0 0 448 512"><path d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z"/></svg>
          Add More Courses
        </a>
      </div>

      <div id="summary" class="w-1/4 px-8 py-10 bg-gray-100">
        <h1 class="font-semibold text-2xl border-b pb-8">Order Summary</h1>
        <div class="flex justify-between mt-10 mb-5">
          <span class="font-semibold text-sm uppercase">Sub Total</span>
          <span class="font-semibold text-sm">{{order.get_order_subtotal}}</span>
        </div>
        <form method="post" name="promo-code">
          {% csrf_token %}
          <div class="py-5">
              <label for="promo-code" class="font-semibold inline-block mb-3 text-sm uppercase">Promo Code</label>
              <input type="text" id="promo-code" name="promo-code" placeholder="Enter your code" class="p-2 text-sm w-full">
          </div>
          <button class="bg-red-500 hover:bg-red-600 px-5 py-2 text-sm text-white uppercase">Apply</button>
        </form>
        {% if order.coupon %}
        <div class="border-t mt-8">
          <div class="flex font-semibold justify-between pt-6 text-sm">
            <span>PROMO</span>
            <span>-{{ order.coupon.get_amount }}</span>
          </div>
        </div>
        {% endif %}
        <div class="border-t mt-8">
          <div class="flex font-semibold justify-between py-6 text-sm">
            <span>TOTAL COST</span>
            <span>{{ order.get_order_total }}</span>
          </div>
          <a href="{% url 'order:payment' %}" class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">Checkout</a>
        </div>
      </div>

    </div>
  </div>


{% endblock content %}

ipm_learning/templates/order/order_summary.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="container mx-auto"> 
    <div class="py-9 px-4 md:px-6 py-12 w-full">
        <div class="">
            <h1 class="text-3xl lg:text-4xl leading-4 lg:leading-9 font-semibold text-gray-800 mt-2">Keranjang Belanja</h1>
        </div>
        <div class="flex lg:flex-row flex-col space-y-8 lg:space-y-0">
            <div class="md:w-full">

            {% for item in order.order_items.all %}
                <div class="w-full flex flex-col md:flex-row items-strech mt-10 md:mt-14 lg:mt-16 pb-12 border-gray-200 border-b">
                    <div class="flex justify-end md:hidden">
                        <a href="{% url 'order:remove-from-cart' item.id %}" class="mt-2">
                            <img src="{% static 'images/shopping-cart-3-svg1.svg' %}" alt="cross" />
                            <!-- <img class="dark:block hidden"  src="https://tuk-cdn.s3.amazonaws.com/can-uploader/shopping-cart-3-svg1dark.svg" alt="cross" /> -->
                        </a>
                    </div>
                    <div class="flex justify-center">
                        <img class="object-center object-cover" src="{{ item.course.thumbnail.url }}" alt="{{ item.course.name }}" role="img" />
                        <img class="object-center object-cover" src="{{ item.comeback_record.comeback.thumbnail.url }}" alt="{{ item.comeback_record.comeback.title }}" role="img" />
                    </div>
                    <div class="md:flex hidden w-full justify-between md:ml-6">
                        <div class="w-full">
                            <div class="flex flex-row justify-between">
                                <div class="flex justify start">
                                    {% if item.course %}
                                        <p class="text-2xl font-semibold leading-normal text-gray-800 ">{{ item.course.name }}</p>
                                    {% else %}
                                        <p class="text-2xl font-semibold leading-normal text-gray-800 ">{{ item.comeback_record.comeback.title }}</p>
                                    {% endif %}
                                </div>
                                <div class="flex justify-end">
                                    
                                </div>
                            </div>
                            
                            <p class="text-base leading-none text-gray-800 mt-4">{{ item.course.get_price }}</p>
                            {% if item.course.discount_pct > 0 %}
                                <p class="text-base leading-none text-red-600 mt-4">Diskon: {{ item.course.get_discount_pct }}</p>
                            {% endif %} 
                            {% if item.course.multi_ticket %}
                                <p class="mt-4 w-11/12 text-base leading-4 text-gray-600">Tickets: {{ item.tickets }}</p>
                            {% endif %}
                            

                            
                            <div class="mt-20 flex w-full items-center justify-between">
                                <div class="w-full flex flex-col h-full md:flex-row justify-between">
                                    
                                    <div class="flex justify-start">
                                        
                                    </div>
                                    <div class="hidden md:block flex justify-end">
                                        
                                        <p class="md:mt-3 text-gray-800 text-right"><span class="text-xl leading-tight text-gray-800"></span><span class="text-xl font-medium">{{ item.get_order_item_total }}</span></p>
                                        <div class="flex justify-end">
                                            <a aria-label="Cancel product" href="{% url 'order:remove-from-cart' item.id %}" class="mt-2 focus:outline-none focus:ring-2 focus:ring-gray-800 rounded">
                                                <img src="{% static 'images/shopping-cart-3-svg1.svg' %}" alt="cross" />
                                                <!-- <img class="dark:block hidden"  src="https://tuk-cdn.s3.amazonaws.com/can-uploader/shopping-cart-3-svg1dark.svg" alt="cross" /> -->
                                           </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div></div>
                    </div>
                    <div class="flex flex-col md:hidden">
                        <div class="flex items-center justify-between">
                            <div>
                                <h2 class="mt-1 text-2xl font-semibold leading-6 text-gray-800">{{ item.course.name }}</h2>
                            </div>
                        </div>
                        <p class="mt-4 w-11/12 text-base leading-4 text-gray-600">{{ item.get_order_item_total }}</p>
                        {% if item.course.discount_pct > 0 %}
                            <p class="mt-4 w-11/12 text-base leading-4 text-red-600">Discount: {{ item.course.get_discount_pct }}</p>
                        {% endif %}
                        
                        {% if item.course.multi_ticket %}
                            <p class="mt-4 w-11/12 text-base leading-4 text-gray-600">Ticket: {{ item.tickets }}</p>
                        {% endif %}
                        <div class="flex items-center justify-end mt-6">
                            
                            <div>
                                <p class="mt:mt-3 text-gray-800 text-right"><span class="text-xl leading-5 text-gray-800"></span><span class="text-xl leading-5 font-medium">{{ item.get_order_item_total }}</span></p>
                            </div>
                            
                        </div>
                    </div>
                </div>
            {% endfor %}
                

            </div>
            <div class="flex justify-center items-center flex-col-reverse md:flex-row md:mt-28 mt-20 w-full">
                <div class="w-full md:w-9/12 lg:w-9/12 p-4 md:p-10 bg-gray-50">
                    <p class="text-2xl font-semibold leading-normal text-gray-800 ">Total Belanja</p>
                    <!-- <p class="text-base leading-4 lg:leading-none text-gray-600 mt-10">Items: {{ order.get_order_item_count }}</p> -->
                    <div class="flex items-center justify-between mt-14">
                        <h3 class="text-base font-medium leading-none text-gray-800 ">Subtotal</h3>
                        <p class="text-base font-medium leading-none text-gray-800 ">{{order.get_order_subtotal}}</p>
                    </div>
                    <div class="flex items-center justify-between mt-10">
                        <form method="post" name="promo-code">
                            {% csrf_token %}
                            <div class="py-5">
                                <label for="promo-code" class="font-semibold inline-block mb-3 text-sm uppercase">Kode Promo</label>
                                <input type="text" id="promo-code" name="promo-code" placeholder="Enter your code" class="p-2 text-sm w-full">
                            </div>
                            <button class="bg-red-500 hover:bg-red-600 px-5 py-2 text-sm text-white rounded">Apply</button>
                          </form>
                          
                    </div>
                    {% if order.course_coupon %}
                          <div class="border-t mt-8">
                            <div class="flex font-semibold justify-between pt-6 text-sm">
                              <span>PROMO '{{ order.course_coupon.code }}'</span>
                              <span>-{{ order.course_coupon.get_amount }}</span>
                            </div>
                          </div>
                    {% endif %}
                    <div class="flex items-center justify-between mt-24">
                        <h3 class="text-xl font-semibold leading-tight text-gray-800">Total Harga</h3>
                        <p class="text-2xl font-semibold text-gray-800">{{ order.get_order_total }}</p>
                    </div>
                    <!-- <a href="{% url 'order:payment' %}"><button class="focus:outline-none hover: focus:ring-2 focus:ring-offset-2 focus:ring-gray-800 w-full mt-4 bg-red-500 text-base font-medium leading-none text-gray-50 hover:bg-red-600 py-5 focus:ring-2 focus:ring-offset-2 focus:ring-gray-800 rounded">Checkout</button></a> -->
                    <!-- <a href="{% url 'order:payment' %}" class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">Checkout</a> -->

                
                    {% if order.order_items.all %}
                        <form method="post" name="checkout">
                            {% csrf_token %}
                            <button class="w-full mt-4 bg-red-500 text-base font-medium leading-none text-gray-50 hover:bg-red-600 py-5 rounded">Bayar</button>
                        </form>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}