config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from ipm_learning.pages.views import AboutPageView, HomePageView, AgencyPageView, subscription
from ipm_learning.content.models import Course

import requests
from django.http import HttpResponse

def serve_ads_txt(request):
    with open('ipm_learning/static/ads.txt', 'r') as file:
        data = file.read()
    return HttpResponse(data, content_type="text/plain")


info_dict = {
    'queryset': Course.objects.all(),
}

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("bahasa-ibu/", AgencyPageView.as_view(), name="bahasa_ibu"),
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
    #     "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # Content
    path("learn/", include("ipm_learning.content.urls", namespace="content")),
    path("order/", include("ipm_learning.order.urls", namespace="order")),
    path("comeback/", include("ipm_learning.comeback.urls", namespace="comeback")),

    # User management
    path("users/", include("ipm_learning.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    
    # Your stuff: custom urls includes go here
    path('subscribe/', subscription, name="subscription"),
    # path("email-test/",TemplateView.as_view(template_name="account/email/payment_success.html")),
    path('tinymce/', include('tinymce.urls')),
    # path('forest', include('django_forest.urls')),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('ads.txt', serve_ads_txt, name='ads_txt'),
    path('sitemap.xml', sitemap,
        {'sitemaps': {'course': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ipm_learning/comeback/urls.py
from django.urls import path
from .views import comeback_main, ComebackJourneyDetail, add_to_waitlist_view

app_name = "comeback"

urlpatterns = [
    path('', comeback_main, name='comeback_main'),
    path('add_to_waitlist/', add_to_waitlist_view, name='add_to_waitlist'),
    path('<slug:slug>/', ComebackJourneyDetail.as_view(), name='comeback_detail'),
]

ipm_learning/content/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, ContentDetailView, CourseLibraryView, EventListView

app_name = "content"

urlpatterns = [
    path("courses/", CourseListView.as_view(), name="course-list"),
    # path("events/", EventListView.as_view(), name="event-list"),
    path("library/", CourseLibraryView.as_view(), name="course-library"),
    path("<slug>/", CourseDetailView.as_view(), name="course-detail"),
    path("<slug>/<content_slug>/", ContentDetailView.as_view(), name="content-detail"),
]

ipm_learning/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path('order-summary/', views.CartView.as_view(), name='summary'),
    path('order-list/', views.OrderListView.as_view(), name='order-list'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('webhooks/xendit/', views.xendit_webhook, name='xendit-webhook'),
]

ipm_learning/users/urls.py
from django.urls import path

from ipm_learning.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    BulkUploadView
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    # path('bulk-import/', BulkUploadView.as_view(), name='bulk-import'),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

ipm_learning/order/forms.py
from django import forms
from .models import OrderItem
from ipm_learning.content.models import Course

class AddToCartForm(forms.ModelForm):

    class Meta:
        model = OrderItem
        exclude = ['order','course']
        widgets = {'any_field': forms.HiddenInput(),}
        # fields = ['quantity', 'colour', 'size']

class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter your code',
    }))

ipm_learning/comeback/views.py
from django.shortcuts import render
from datetime import date
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .models import ComebackJourney, ComebackRecord
from ipm_learning.order.models import OrderItem, CourseRecord
from ipm_learning.order.utils import get_or_set_order_session
from django.shortcuts import redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .models import ComebackWaitlist
from django.contrib.auth.decorators import login_required


def comeback_main(request):
    journey = ComebackJourney.objects.filter(is_active=True).first()
    registration = False
    current_date = date.today()
    
    if journey and journey.signup_start_date <= current_date <= journey.signup_end_date and journey.remaining_spots > 0:
        registration = True

    
    # Check if the user is authenticated and if they are on the waitlist
    on_waitlist = False
    if request.user.is_authenticated:
        on_waitlist = ComebackWaitlist.objects.filter(user=request.user).exists()

    context = {
        'journey': journey,
        'registration': registration,
        'on_waitlist': on_waitlist,
    }
    
    if request.method == 'POST':
        order = get_or_set_order_session(request)
        
        if not request.user.is_authenticated:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
        else:
            if request.POST.get('pmt_type') == 'monthly':
                is_monthly_pmt = True
            else:
                is_monthly_pmt = False
                
            comeback_record = ComebackRecord.objects.filter(comeback=journey, user=request.user).first()
            
            if comeback_record and comeback_record.is_active:
                messages.info(request, "This item is already in your library")
                return redirect("content:course-library")
            else:
                if comeback_record:
                    comeback_record.delete()
                comeback_record = ComebackRecord.objects.create(
                user = request.user,
                comeback = journey,
                is_monthly_pmt = is_monthly_pmt,
                one_time_price = journey.one_time_price,
                monthly_price = journey.monthly_price,
                num_monthly_pmts = journey.num_monthly_pmts,   
            )
        
            item_filter_lst = order.order_items.filter(comeback_record=comeback_record)
            
            if not item_filter_lst.exists():
                new_item = OrderItem.objects.create(
                    comeback_record = comeback_record,
                    order = order,
                    tickets = 1,
                )
                return redirect("order:summary")
            else:
                messages.info(request, "This item is already in your cart")
                return redirect("order:summary") 
    
    return render(request, 'comeback/comeback_main.html', context)



class ComebackJourneyDetail(LoginRequiredMixin, generic.DetailView):
    model = ComebackJourney
    template_name = "comeback/comeback_detail.html"
    context_object_name = "comeback_journey"
    slug_url_kwarg = 'slug'
    slug_field = 'slug'  # Adjust the slug field accordingly

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        user = self.request.user
        comeback_journey = self.get_object()

        try:
            # Check if user has an associated ComebackRecord
            comeback_record = ComebackRecord.objects.get(user=user, comeback=comeback_journey)

            # Check if the record is live
            comeback_record.is_live = comeback_record.comeback.course_start_date <= date.today()

            # Retrieve CourseRecords only if the record is live
            if comeback_record.is_live:
                context['course_records'] = CourseRecord.objects.filter(user=user, comeback_record=comeback_record)
            else:
                context['course_records'] = []

            context['comeback_record'] = comeback_record
        except ComebackRecord.DoesNotExist:
            # If no associated ComebackRecord is found, set course_records to an empty list
            context['course_records'] = []

        return context
    
    
class AddToWaitlistView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
            # Create a new waitlist entry for the current user
            ComebackWaitlist.objects.create(user=request.user)
            # Redirect the user to a thank you page or back to the main page
            return redirect(reverse('comeback:comeback_main') + '#journeySection')
        
@login_required
def add_to_waitlist_view(request):
    if request.method == 'POST':
        # Create a new waitlist entry for the current user
        ComebackWaitlist.objects.create(user=request.user)
        # Redirect the user to a thank you page or back to the main page
        return redirect(reverse('comeback:comeback_main') + '#waitlist')

ipm_learning/pages/views.py
from django.shortcuts import redirect
from django.contrib import messages
from django.shortcuts import render
from django.views import generic
from django.db.models import Q
from ipm_learning.content.models import Course
from .models import PromotedCourse, Testimonial, TeamMember, PageContent, Article
from django.conf import settings
from mailchimp_marketing import Client
from mailchimp_marketing.api_client import ApiClientError

# Create your views here.

class AboutPageView(generic.TemplateView):
    template_name = 'pages/about.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_content'] = PageContent.objects.get(page_title='About')
        return context
    
class AgencyPageView(generic.TemplateView):
    template_name = 'pages/bahasa_ibu.html'
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['page_content'] = PageContent.objects.get(page_title='About')
    #     return context


class HomePageView(generic.TemplateView):
    template_name = 'pages/home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        events = Course.objects.filter(
            (Q(course_type="Event") | Q(course_type="Bootcamp")) & Q(active=True)
            ).order_by('event_datetime')[:3]
        
        # courses = Course.objects.filter(
        #     Q(course_type="Course") & Q(active=True)
        # )[:6]
        
        promo_courses = PromotedCourse.objects.all()
        
        testimonials = Testimonial.objects.all().order_by('?')[:6]
        teammembers = TeamMember.objects.all()
        articles = Article.objects.order_by().order_by('-id')[:4]
        
        context['next_event'] = events[:1].first()
        context['remaining_events'] = events[1:]
        context['courses'] = promo_courses
        context['testimonials'] = testimonials
        context['teammembers'] = teammembers
        context['articles'] = articles
        return context
    


# Mailchimp Settings
api_key = settings.MAILCHIMP_API_KEY
server = settings.MAILCHIMP_DATA_CENTER
list_id = settings.MAILCHIMP_EMAIL_LIST_ID
   

def subscription(request):
    if request.method == "POST":
        email = request.POST['email']
        next = request.POST['next']

        # Communicate with Mailchimp API
        mailchimp = Client()
        mailchimp.set_config({
            "api_key": api_key,
            "server": server,
        })

        member_info = {
            "email_address": email,
            "status": "subscribed",
        }

        try:
            response = mailchimp.lists.add_list_member(list_id, member_info)
            print("response: {}".format(response))
            messages.info(request, "Sudah Berlangganan!")
        except ApiClientError as error:
            print("An exception occurred: {}".format(error.text))
            messages.info(request, "Gagal Berlangganan karena format yang salah atau sudah berlangganan")

        # messages.success(request, "Email received. thank You! ")
    return redirect(next)

ipm_learning/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView, TemplateView
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from ipm_learning.order.models import Order
import io, csv

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        queryset = Order.objects.filter(
            user=user
        )
        context["orders"] = queryset
        return context
  


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name", "phone_number"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class BulkUploadView(TemplateView):
    def get(self, request):
        template_name = 'users/bulk_import.html'
        return render(request, template_name)

    def post(self, request):
        paramFile = io.TextIOWrapper(request.FILES['userfile'].file)
        portfolio1 = csv.DictReader(paramFile)
        list_of_dict = list(portfolio1)
        objs = [
            User(
                name=row['name'],
                username=row['email'],
                email=row['email'],
            )
            for row in list_of_dict
        ]
        try:
            msg = User.objects.bulk_create(objs)
            returnmsg = {"status_code": 200}
            print('imported successfully')
        except Exception as e:
            print('Error While Importing Data: ', e)
            returnmsg = {"status_code": 500}
            


        return JsonResponse(returnmsg)

ipm_learning/templates/content/course_library.html
{% extends "base.html" %}

{% load filter_tag %}

{% block content %}

  <section class="text-gray-600 body-font">

    {% if comeback_records %}
    <div class="container px-5 py-16 mx-auto">
      <div class="flex flex-col">

        <div class="h-1 bg-gray-200 rounded overflow-hidden">
          <div class="w-24 h-full bg-red-500"></div>
        </div>
        <div class="flex flex-wrap sm:flex-row flex-col py-6 mb-12">
          <h1 class="sm:w-2/5 text-gray-900 font-medium title-font text-2xl mb-2 sm:mb-0">Comeback Journey</h1>
        </div>
      </div>
      <div class="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
          {% for comeback_record in comeback_records %}
            <div class="p-4 md:w-1/3 sm:mb-0 mb-6">
              <div class="rounded-lg h-64 overflow-hidden">
                {% if comeback_record.is_live %}
                  <a href="{% url 'comeback:comeback_detail' slug=comeback_record.comeback.slug %}">
                    <img alt="content" class="object-cover object-center h-full w-full" src="{{ comeback_record.comeback.thumbnail.url }}">
                </a>
                {% else %}
                  <a href="#">
                    <img alt="content" class="object-cover object-center h-full w-full" src="{{ comeback_record.comeback.thumbnail.url }}">
                  </a>
                {% endif %}
              </div>
              <h2 class="text-xl font-medium title-font text-gray-900 mt-5">{{ comeback_record.comeback.title }}</h2>
              
              <!-- <p class="text-base leading-relaxed mt-2">Start Date: {{ course_record.created_at }}</p> -->
              {% if comeback_record.is_live %}
                <span class="inline-block py-1 px-2 rounded bg-red-500 text-white text-xs font-medium tracking-widest">Live!</span>
              {% else %}
                <span class="inline-block py-1 px-2 rounded bg-gray-500 text-white text-xs font-medium tracking-widest">Starting Soon</span>
              {% endif %}
              
              <p class="text-base leading-relaxed mt-2">Yang Ibu Dapatkan: {{ comeback_record.comeback.course_start_date }}</p>
              
              {% if comeback_record.is_live %}
              <a href="{% url 'comeback:comeback_detail' slug=comeback_record.comeback.slug %}" class="text-red-500 inline-flex items-center mt-3">Kembali ke Kursus Online
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewbox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
              {% endif %}
            </div>
          {% endfor %}
        
      </div>
    </div>
    {% endif %}

    <div class="container px-5 py-16 mx-auto">
      <div class="flex flex-col">

        <div class="h-1 bg-gray-200 rounded overflow-hidden">
          <div class="w-24 h-full bg-red-500"></div>
        </div>
        <div class="flex flex-wrap sm:flex-row flex-col py-6 mb-12">
          <h1 class="sm:w-2/5 text-gray-900 font-medium title-font text-2xl mb-2 sm:mb-0">Aktivitasku</h1>
        </div>
      </div>
      <div class="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
        {% if course_records %}
          {% for course_record in course_records %}
            <div class="p-4 md:w-1/3 sm:mb-0 mb-6">
              <div class="rounded-lg h-64 overflow-hidden">
                <a href="{{ course_record.course.contents.first.get_absolute_url }}">
                  <img alt="content" class="object-cover object-center h-full w-full" src="{{ course_record.course.thumbnail.url }}">
                </a>
              </div>
              <h2 class="text-xl font-medium title-font text-gray-900 mt-5">{{ course_record.course.name }}</h2>
              <h2 class="text-sm title-font text-gray-500 tracking-widest">{{ course_record.course.category }} | {{ course_record.course.course_type }}</h2>
              <!-- <p class="text-base leading-relaxed mt-2">Start Date: {{ course_record.created_at }}</p> -->
              {% if course_record.modules_complete == course_record.module_count %}
                <span class="inline-block py-1 px-2 rounded bg-red-500 text-white text-xs font-medium tracking-widest">Lulus</span>
              {% else %}
                <span class="inline-block py-1 px-2 rounded bg-gray-500 text-white text-xs font-medium tracking-widest">Dalam Proses</span>
              {% endif %}
              {% if course_record.tickets > 1 %}
                <p class="text-base leading-relaxed mt-2">Tickets: {{ course_record.tickets }}</p>
              {% endif %}
              <p class="text-base leading-relaxed mt-2">Yang Ibu Dapatkan: {{ course_record.module_count }}</p>
              <p class="text-base leading-relaxed mt-2">
              {% for quiz_record in course_record|filter_quiz_records %}
                {% if quiz_record.quiz_attempts > 0%}
                <p>{{ quiz_record.content.title}} Score: {{ quiz_record.quiz_correct_ans }} / {{ quiz_record.quiz_questions }}</p>
                {% endif %}
              {% endfor %}
              </p>
              
              <a href="{{ course_record.course.contents.first.get_absolute_url }}"class="text-red-500 inline-flex items-center mt-3">Kembali ke Kursus Online
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewbox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          {% endfor %}
        {% else %}
          <div class="relative container px-4 pt-12 mb-20 mx-auto text-center">
            <h1 class="sm:text-4xl text-3xl font-medium title-font text-gray-900">Belum ada aktivitas!</h1>
            <a href="{% url 'content:course-list' %}" class="relative z-10 inline-block w-full md:w-auto mb-2 md:mb-0 mt-5 px-8 py-4 mr-4 text-sm font-medium leading-normal bg-red-400 hover:bg-red-300 text-white rounded transition duration-200">Cek Aktivitas</a>
          </div>
        {% endif %}
      </div>
    </div>

  </section>

{% endblock content %}

ipm_learning/templates/content/course_list.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-600 body-font" x-data="courseSearch()">

  <div class="px-4">
    <div class="flex flex-col text-start w-full mt-7 mb-5">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Acara dan Kursus</h1>
    </div>
    <div class="h-1 bg-gray-200 rounded mb-7 mx-auto">
        <div class="w-24 h-full bg-red-500"></div>
    </div>
  </div>

  <!-- Collapsible Filter Menu for Mobile -->
  <div class="lg:hidden px-4 py-4">
    <button @click="showFilters = !showFilters" class="w-full text-left bg-gray-200 p-2 rounded">Search & Filter</button>
    <div x-show="showFilters" class="mt-4">
        <!-- Your filter form for mobile goes here -->
        <form hx-get="{% url 'content:course-list' %}" hx-target="#course-list" hx-swap="innerHTML" id="course-search-form">
          <!-- Search input -->
          <div class="mb-4">
            <!-- {% if search_query %} -->
            <!-- <p class="mb-2 text-gray-700">"{{ search_query }}"</p> -->
            <!-- {% endif %} -->
            <input type="text" name="search" placeholder="Mencari" x-model="searchQuery" @input="debounce(submitForm, 300)" class="w-full px-4 py-2 border rounded">
          </div>
          
          <!-- Course Type Filter -->
          <div class="mb-4">
            <h4 class="mb-2 font-medium">Jenis Kursus:</h4>
            {% for type, display_name in type_choices %}
            <label>
                <input type="checkbox" name="course_type" value="{{ type }}" checked class="mr-2"> {{ display_name }}
            </label><br>
            {% endfor %}
          </div>

          <!-- Category Filter -->
          <div class="mb-4">
              <h4 class="mb-2 font-medium">Kategori:</h4>
              {% for category in categories %}
                  <label><input type="checkbox" name="category" value="{{ category.id }}" checked class="mr-2"> {{ category.name }}</label><br>
              {% endfor %}
          </div>

          <!-- Price Filter -->
          <div class="mb-4">
              <h4 class="mb-2 font-medium">Harga:</h4>
              <label><input type="checkbox" name="price" value="free" checked class="mr-2"> Gratis</label><br>
              <label><input type="checkbox" name="price" value="paid" checked class="mr-2"> Berbayar</label>
          </div>

          <!-- Search and Clear buttons -->
          <div class="mt-6">
              <button type="submit" class="mr-2 py-2 px-4 text-white bg-red-400 rounded hover:bg-red-300">Mencari</button>
              <button type="button" @click="clearSearchAndRefresh()" class="py-2 px-4 bg-gray-200 rounded hover:bg-gray-300">Jernih</button>
          </div>
      </form>
    </div>
</div>

  <!-- Flex layout for sidebar and main content -->
  <div class="flex">

    

    <!-- Filter Form for Desktop -->
    <section class="hidden lg:block relative py-4">
        <div class="container px-4 mx-auto">
            <div class="max-w-md mx-auto py-6 lg:py-12 px-4 lg:px-8 bg-white border rounded-xl">
                <form hx-get="{% url 'content:course-list' %}" hx-target="#course-list" hx-swap="innerHTML" id="course-search-form">
                    <!-- Search input -->
                    <div class="mb-4">
                      <!-- {% if search_query %} -->
                      <!-- <p class="mb-2 text-gray-700">"{{ search_query }}"</p> -->
                      <!-- {% endif %} -->
                      <input type="text" name="search" placeholder="Mencari" x-model="searchQuery" @input="debounce(submitForm, 300)" class="w-full px-4 py-2 border rounded">
                    </div>
                    
                    <!-- Course Type Filter -->
                    <div class="mb-4">
                      <h4 class="mb-2 font-medium">Jenis Kursus:</h4>
                      {% for type, display_name in type_choices %}
                      <label>
                          <input type="checkbox" name="course_type" value="{{ type }}" checked class="mr-2"> {{ display_name }}
                      </label><br>
                      {% endfor %}
                    </div>

                    <!-- Category Filter -->
                    <div class="mb-4">
                        <h4 class="mb-2 font-medium">Kategori:</h4>
                        {% for category in categories %}
                            <label><input type="checkbox" name="category" value="{{ category.id }}" checked class="mr-2"> {{ category.name }}</label><br>
                        {% endfor %}
                    </div>

                    <!-- Price Filter -->
                    <div class="mb-4">
                        <h4 class="mb-2 font-medium">Harga:</h4>
                        <label><input type="checkbox" name="price" value="free" checked class="mr-2"> Gratis</label><br>
                        <label><input type="checkbox" name="price" value="paid" checked class="mr-2"> Berbayar</label>
                    </div>

                    <!-- Search and Clear buttons -->
                    <div class="mt-6 flex space-x-2">
                      <button type="submit" class="flex-1 mr-2 py-2 px-4 text-white bg-red-400 rounded hover:bg-red-300">Mencari</button>
                      <button type="button" @click="clearSearchAndRefresh()" class="flex-1 py-2 px-4 bg-gray-200 rounded hover:bg-gray-300">Jernih</button>
                    </div>
                </form>
                
            </div>
        </div>
    </section>

    <!-- Main content for displaying courses -->
    <div class="w-full lg:w-3/4 p-4" id="course-list">
        {% include "content/course_list_partial.html" %}
  </div>

</section>

<script src="https://unpkg.com/htmx.org@1.6.1"></script>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>

<script>
  function debounce(callback, wait) {
    let timeoutId = null;
    return (...args) => {
        clearTimeout(timeoutId);
        timeoutId = setTimeout(() => {
            callback.apply(null, args);
        }, wait);
    };
  }

  function courseSearch() {
      return {
          searchQuery: '',
          showFilters: false,  // For the mobile filter menu visibility
          submitForm() {
              document.getElementById('course-search-form').submit();
          },
          clearSearchAndRefresh() {
              window.location.href = "{% url 'content:course-list' %}";
          }
      };
  }
</script>
{% endblock content %}

ipm_learning/templates/content/course_list_partial.html
<div class="mb-4">
    <h2 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900"></h1>
    <h3 class="mb-6 text-2xl font-semibold ">{{ course_list.count }} Kursus</h3>
  </div>

<div class="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
    {% for course in course_list %}
        <div class="p-4 md:w-1/2 sm:mb-0 mb-6">
            <div class="rounded-lg h-64 overflow-hidden">
            <a href="{% url 'content:course-detail' course.slug %}">
                <img alt="content" class="object-cover object-center h-full w-full" src="{{ course.thumbnail.url }}">
            </a>
            </div>
            <h2 class="text-xl font-medium title-font text-gray-900 mt-5">{{ course.name }}</h2>
            <h2 class="text-sm title-font text-gray-500 tracking-widest">{{ course.course_type }}</h2>
            {% if course.event_datetime %}
                <p class="text-base leading-relaxed mt-2">{{ course.event_datetime|date }} at {{ course.event_datetime|time }}</p>
            {% endif %}
            <p class="text-base leading-relaxed mt-2">{{ course.description }}</p>
            <a href="{% url 'content:course-detail' course.slug %}" class="text-red-500 inline-flex items-center mt-3">Learn More
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
            </a>
        </div>
    {% endfor %}

</div>